find_path(XQILLA_INCLUDE_DIR NAMES xqilla/xqilla-simple.hpp)
find_path(XQILLA_LIBRARY_DIR NAMES libxqilla.dylib libxerces-c.a libxerces-c.la libxerces-c.so PATH_SUFFIXES lib  PATHS "/usr/lib/x86_64-linux-gnu" )
find_library(XQILLA_LIBRARY NAMES xqilla)
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(XQILLA DEFAULT_MSG XQILLA_INCLUDE_DIR XQILLA_LIBRARY_DIR XQILLA_LIBRARY)
mark_as_advanced(XQILLA_INCLUDE_DIR XQILLA_LIBRARY)
#MESSAGE(STATUS "DEBUG -- XQILLA_INCLUDE_DIR ${XQILLA_INCLUDE_DIR}" )
#MESSAGE(STATUS "DEBUG -- XQILLA_LIBRARY_DIR ${XQILLA_LIBRARY_DIR}" )
#MESSAGE(STATUS "DEBUG -- XQILLA_LIBRARY ${XQILLA_LIBRARY}" )
